version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      PATHWAY_PORT: "${PATHWAY_PORT:-8000}"
      PATHWAY_LICENSE_KEY: "${PATHWAY_LICENSE_KEY:-F2379D-E3102B-FC228C-3FC6BE-EF4E40-V3}"
    ports:
      - "${PATHWAY_PORT:-8000}:${PATHWAY_PORT:-8000}"
    networks:
      - network
    volumes:
      - ./data:/app/data
      - ./Cache:/app/Cache
      - ./storage/pw_dump_files:/app/storage/pw_dump_files
      - ./storage/pw_dump_images:/app/storage/pw_dump_images
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  nginx:
    build:
      context: nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - network
    volumes:
      - ./storage/pw_dump_files:/app/pw_dump_files
      - ./storage/pw_dump_images:/app/pw_dump_images

  ui:
    build:
      context: ui
    environment:
      PATHWAY_HOST: "app"
      PATHWAY_PORT: "${PATHWAY_PORT:-8000}"
      UI_PORT: 8501
    ports:
      - "8501:8501"
    networks:
      - network
    volumes:
      - ./ui:/ui.py

networks:
  network:
    driver: bridge
